SAR_SETTINGS:
  SAR_Type: Source_One_V5
  SAR_Config: A15_L200
PLANE_SETTINGS:
  Plane_Type: Landing_Surface
  Plane_Config: Checkerboard_L02
ENV_SETTINGS:
  Env_Name: SAR_2D_DeepRL_Env
  V_mag_Limts:
  - 1.5
  - 4.5
  V_angle_Limits:
  - 10
  - 90
  Plane_Angle_Limits:
  - 0
  - 0
  Ang_Acc_Limits:
  - -100
  - 0
MODEL_SETTINGS:
  Mass_Std: 0.0
  Iyy_Std: 0.0
  Ref_Mass: 0.792
  Ref_Ixx: 0.0064
  Ref_Iyy: 0.00594
  Ref_Izz: 0.00569
  L_eff: 0.21481
  Gamma_eff: 15.07
  Forward_Reach: 0.15
LEARNING_MODEL:
  Policy: SACPolicy
  Observation_Layer: 4
  Network_Layers:
    pi:
    - 10
    - 10
    - 10
    qf:
    - 64
    - 64
    - 64
  Action_Layer: 4
  Action_Space_High:
  - 1.0
  - 1.0
  Action_Space_Low:
  - -1.0
  - -1.0
  Gamma: 0.999
  Learning_Rate: 0.002
REWARD_SETTINGS:
  W_Dist: 0.5
  W_tau_cr: 0.5
  W_tx: 2.0
  W_LT: 1.0
  W_GM: 1.0
  W_Phi_rel: 2.0
  W_Legs: 2.0
