P_kp_xy: 0.5
P_kd_xy: 0.4
P_ki_xy: 0.0
i_range_xy: 0.3 

P_kp_z: 1.20
P_kd_z: 0.35
P_ki_z: 0.0
i_range_z: 0.25

R_kp_xy: 0.004
R_kd_xy: 0.0017
R_ki_xy: 0.0
i_range_R_xy: 1.0


R_kp_z: 0.003
R_kd_z: 0.001
R_ki_z: 0.002
i_range_R_z: 0.5

