## POSITION XY
P_kp_xy: 0.5
P_kd_xy: 0.4
P_ki_xy: 0.0
i_range_xy: 0.3 

## POSITION Z
P_kp_z: 1.20
P_kd_z: 0.35
P_ki_z: 0.0
i_range_z: 0.25

## ORIENTATION XY
R_kp_xy: 0.03
R_kd_xy: 0.0025
R_ki_xy: 0.0
i_range_R_xy: 1.0

## ORIENTATION Z
R_kp_z: 0.000
R_kd_z: 0.00
R_ki_z: 0.0
i_range_R_z: 0.5

