Plane_Config:

  Flight_Cage:
    Plane_Angle: 180  # [deg]
    Pos_X: 0    # [m]
    Pos_Y: 0    # [m]
    Pos_Z: 2.1  # [m]

  180_deg: # Ceiling
    Plane_Angle: 180  # [deg]
    Pos_X: 0    # [m]
    Pos_Y: 0    # [m]
    Pos_Z: 2.0  # [m]


  135_deg:
    Plane_Angle: 135  # [deg]
    Pos_X: 2.0  # [m]
    Pos_Y: 0.0  # [m]
    Pos_Z: 2.0  # [m]

  90_deg:
    Plane_Angle: 90   # [deg]
    Pos_X: 2.0  # [m]
    Pos_Y: 0.0  # [m]
    Pos_Z: 0.5  # [m]

  45_deg:
    Plane_Angle: 45   # [deg]
    Pos_X: 2.0  # [m]
    Pos_Y: 0.0  # [m]
    Pos_Z: 0.5  # [m]

  0_deg:  # Ground
    Plane_Angle: 0   # [deg]
    Pos_X: 2.0  # [m]
    Pos_Y: 0.0  # [m]
    Pos_Z: 0.0  # [m]

