DATA_TYPE: "SIM"

ENV_SETTINGS:
  Ground_Name: "GroundPlane_Desert_Physical"

PLANE_SETTINGS:
  Plane_Model: "Standard_Plane"
  Plane_Config: "180_deg"

QUAD_SETTINGS:
  CF_Type: "Standard"
  CF_Config: "Narrow_Long"
  Cam_Sensor: False

  Policy_Type: "PARAM_OPTIM"
  # Policy_Type: "SVL_POLICY" 
  # Policy_Type: "DEEP_RL" 

SIM_SETTINGS:
  GUI_Flag: True
  Pause_Flag: False
  Sim_Speed: 2.0
  Sim_Slowdown_Speed: 0.4
  Landing_Slowdown_Flag: True

CF_DC_SETTINGS:
  Console_Rate: 50 # [Hz]
  Logging_Rate: 10 # [Hz]






