DATA_TYPE: "SIM"
SURFACE_NAME: "CeilingPlane_Large"
GROUND_NAME: "GroundPlane_Desert_Physical"

GUI_FLAG: True
PAUSE_FLAG: True
CONSOLE_RATE: 20 # [Hz]
LOGGING_RATE: 50 # [Hz]

SIM_SPEED: 0.5
SIM_SLOWDOWN_SPEED: 0.1
LANDING_SLOWDOWN_FLAG: True


K_EP_MAX: 15
CEILING_HEIGHT: 2.1

POLICY_TYPE: "PARAM_OPTIM" 
# POLICY_TYPE: "SVL_POLICY" 
# POLICY_TYPE: "DEEP_RL" 

CAM_SENSOR: False



