DATA_TYPE: "SIM"

ENV_SETTINGS:
  Ceiling_Height: 2.1
  Surface_Name: "CeilingPlane_Large"
  Ground_Name: "GroundPlane_Desert_Physical"

PLANE_SETTINGS:
  Plane_Model: "Test_Plane2"
  Plane_Config: "0_deg"

QUAD_SETTINGS:
  CF_Type: "Standard"
  Config: "Narrow_Long"
  Cam_Sensor: False

  Policy_Type: "PARAM_OPTIM"
  # Policy_Type: "SVL_POLICY" 
  # Policy_Type: "DEEP_RL" 

SIM_SETTINGS:
  GUI_Flag: True
  Pause_Flag: True
  Sim_Speed: 0.5
  Sim_Slowdown_Speed: 0.4
  Landing_Slowdown_Flag: True

CF_DC_SETTINGS:
  Console_Rate: 50 # [Hz]
  Logging_Rate: 10 # [Hz]






