MODEL_NAME: "crazyflie_Wide-Long"
GUI_FLAG: False

SIM_SPEED: 1.0
SIM_SLOWDOWN_SPEED: 0.2
LANDING_SLOWDOWN: true


K_EP_MAX: 250
CTRL_DEBUG_SLOWDOWN: 2
CEILING_HEIGHT: 2.1
CF_MASS: 0.0376

POLICY_TYPE: 1 # 0: RL POLICY 1: NN POLICY


