DATA_TYPE: "SIM"
SURFACE_NAME: "CeilingPlane_Large"
GROUND_NAME: "GroundPlane_Desert_Physical"

# ENV_SETTINGS:
#  Ceiling_Height: 2.1
#  Surface_Name: "CeilingPlane_Large"
#  Ground_Name: "GroundPlane_Desert_Physical"

QUAD_SETTINGS:
  CF_Type: "Standard"
  Config: "Narrow_Long"

GUI_FLAG: True
PAUSE_FLAG: True
CONSOLE_RATE: 50 # [Hz]
LOGGING_RATE: 50 # [Hz]

SIM_SPEED: 1.0
SIM_SLOWDOWN_SPEED: 0.3
LANDING_SLOWDOWN_FLAG: True

CEILING_HEIGHT: 2.1

# POLICY_TYPE: "PARAM_OPTIM" 
# POLICY_TYPE: "SVL_POLICY" 
POLICY_TYPE: "DEEP_RL" 

CAM_SENSOR: False



