DATA_TYPE: "SIM"
SURFACE_NAME: "FlightCage"
GROUND_NAME: "GroundPlane_Desert_Physical"

GUI_FLAG: True
PAUSE_FLAG: False
CONSOLE_RATE: 20 # [Hz]
LOGGING_RATE: 50 # [Hz]

SIM_SPEED: 0.5
SIM_SLOWDOWN_SPEED: 0.5
LANDING_SLOWDOWN_FLAG: True


K_EP_MAX: 15
CEILING_HEIGHT: 2.1

POLICY_TYPE: 0 # 0: RL POLICY 1: NN POLICY


