MODEL_NAME: "crazyflie_Wide-Short"
SURFACE_NAME: "CeilingPlane_Large"
GROUND_NAME: "GroundPlane_Desert_Visual"

GUI_FLAG: False
PAUSE_FLAG: True
LOGGING_FLAG: False

SIM_SPEED: 0.01
SIM_SLOWDOWN_SPEED: 0.01
LANDING_SLOWDOWN_FLAG: True


K_EP_MAX: 250
CEILING_HEIGHT: 2.1
CF_MASS: 0.0376

POLICY_TYPE: 0 # 0: RL POLICY 1: NN POLICY


