MODEL_NAME: "crazyflie_Narrow-Long"
WORLD_NAME: "CeilingSurface_Large"
GUI_FLAG: True

SIM_SPEED: 0.3
SIM_SLOWDOWN_SPEED: 0.1
LANDING_SLOWDOWN: True


K_EP_MAX: 250
CTRL_DEBUG_SLOWDOWN: 2
CEILING_HEIGHT: 2.1
CF_MASS: 0.0376

POLICY_TYPE: 1 # 0: RL POLICY 1: NN POLICY


