DATA_TYPE: "SIM"
SURFACE_NAME: "CeilingPlane_Large"
GROUND_NAME: "GroundPlane_Desert_Visual"

GUI_FLAG: True
PAUSE_FLAG: False
LOGGING_FLAG: False

SIM_SPEED: 1.5
SIM_SLOWDOWN_SPEED: 0.2
LANDING_SLOWDOWN_FLAG: True


K_EP_MAX: 2
CEILING_HEIGHT: 2.1

POLICY_TYPE: 0 # 0: RL POLICY 1: NN POLICY


