DATA_TYPE: "SIM"

ENV_SETTINGS:
  Ground_Name: "GroundPlane_None"

PLANE_SETTINGS:
  Plane_Model: "Standard_Plane"
  Plane_Config: "45_deg"

QUAD_SETTINGS:
  CF_Type: "Standard"
  CF_Config: "A60_L75_K32"


  Cam_Sensor: False

  # Policy_Type: "PARAM_OPTIM"
  # Policy_Type: "SVL_POLICY" 
  # Policy_Type: "DEEP_RL" 
  Policy_Type: "DEEP_RL_SB3" 


SIM_SETTINGS:
  GUI_Flag: True
  Pause_Flag: False
  Sim_Speed: 0.6
  Sim_Slowdown_Speed: 0.4
  Landing_Slowdown_Flag: True

CF_DC_SETTINGS:
  Console_Rate: 50 # [Hz]
  Logging_Rate: 10 # [Hz]






