<<<<<<< HEAD
MODEL_NAME: "crazyflie_Wide-Long"
=======
MODEL_NAME: "crazyflie_Narrow-Long"
>>>>>>> c2af9fe2ae28717325b5cae7986274101337dc56
GUI_FLAG: false

SIM_SPEED: 2.5
SIM_SLOWDOWN_SPEED: 0.4
LANDING_SLOWDOWN: true
K_EP_SLOWDOWN: 0


K_EP_MAX: 16
CEILING_HEIGHT: 2.1
CF_MASS: 0.0376


# controller: "GTC"
