DATA_TYPE: "SIM"
SURFACE_NAME: "CeilingPlane_Large"
GROUND_NAME: "GroundPlane_Desert_Visual"

GUI_FLAG: False
PAUSE_FLAG: False
CONSOLE_RATE: 20 # [Hz]
LOGGING_RATE: 20 # [Hz]

SIM_SPEED: 2.5
SIM_SLOWDOWN_SPEED: 0.4
LANDING_SLOWDOWN_FLAG: True


K_EP_MAX: 18
CEILING_HEIGHT: 2.1

POLICY_TYPE: 0 # 0: RL POLICY 1: NN POLICY


