DATA_TYPE: "SIM"
SURFACE_NAME: "CeilingPlane_Large"
GROUND_NAME: "GroundPlane_Desert_Physical"

GUI_FLAG: False
PAUSE_FLAG: False
LOGGING_FLAG: False

SIM_SPEED: 0.01
SIM_SLOWDOWN_SPEED: 0.01
LANDING_SLOWDOWN_FLAG: True


K_EP_MAX: 2
CEILING_HEIGHT: 2.1

POLICY_TYPE: 0 # 0: RL POLICY 1: NN POLICY


