MODEL_NAME: "crazyflie_Wide-Short"
GUI_FLAG: true

SIM_SPEED: 0.8
SIM_SLOWDOWN_SPEED: 0.8
LANDING_SLOWDOWN: true


K_EP_MAX: 16
CTRL_DEBUG_SLOWDOWN: 30
CEILING_HEIGHT: 2.1
CF_MASS: 0.0376


# controller: "GTC"
