DATA_TYPE: "SIM"
SURFACE_NAME: "CeilingPlane_Large"
GROUND_NAME: "GroundPlane_Desert_Physical"

GUI_FLAG: True
PAUSE_FLAG: False
CONSOLE_RATE: 20 # [Hz]
LOGGING_RATE: 50 # [Hz]

SIM_SPEED: 0.05
SIM_SLOWDOWN_SPEED: 0.01
LANDING_SLOWDOWN_FLAG: False


K_EP_MAX: 30
CEILING_HEIGHT: 2.1

POLICY_TYPE: 1 # 0: RL POLICY 1: NN POLICY
CAM_SENSOR: True


