<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="crazyflie" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="width" value="1.0" />   <!-- Beams are square in length and width -->
    <xacro:property name="height1" value="2" />   <!-- Link 1 -->
    <!-- Base Link -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${height1}"/>
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${height1}"/>
            </geometry>
        </collision>

        <inertial>
            <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
            <mass value="1"/>
            <inertia
            ixx="1.0" ixy="0.0" ixz="0.0"
            iyy="1.0" iyz="0.0"
            izz="1.0"/>
        </inertial>
    </link>

</robot>