SAR_SETTINGS:
  SAR_Type: Crazyflie
  SAR_Config: A10_L70
PLANE_SETTINGS:
  Plane_Type: Landing_Surface
  Plane_Config: Checkerboard_L02
ENV_SETTINGS:
  Env_Name: SAR_2D_DeepRL_Env
  V_mag_Limts:
  - 1.0
  - 5.0
  V_angle_Limits:
  - 5
  - 95
  Plane_Angle_Limits:
  - 0
  - 0
  Ang_Acc_Limits:
  - -90
  - 0
MODEL_SETTINGS:
  Mass_Std: 0.0
  Iyy_Std: 0.0
  Ref_Mass: 0.05078
  Ref_Ixx: 7.15e-05
  Ref_Iyy: 7.2e-05
  Ref_Izz: 6.26e-05
  L_eff: 0.07842
  Gamma_eff: 27.57
  Forward_Reach: 0.057
LEARNING_MODEL:
  Policy: SACPolicy
  Observation_Layer: 4
  Network_Layers:
    pi:
    - 10
    - 10
    - 10
    qf:
    - 64
    - 64
    - 64
  Action_Layer: 4
  Action_Space_High:
  - 1.0
  - 1.0
  Action_Space_Low:
  - -1.0
  - -1.0
  Gamma: 0.999
  Learning_Rate: 0.0015
REWARD_SETTINGS:
  W_Dist: 0.1
  W_tau_cr: 0.1
  W_tx: 1.0
  W_LT: 1.0
  W_GM: 1.0
  W_Phi_rel: 1.0
  W_Legs: 2.0
