PLANE_SETTINGS:
  Plane_Model: Standard_Plane
  Plane_Angle: 135
  Plane_Pos:
    X: 2.0
    Y: 0.0
    Z: 2.0
QUAD_SETTINGS:
  CF_Type: Standard
  CF_Config: Narrow_Long
TEST_SETTINGS:
  Vel_Limts: c
  Phi_Limits: d
LEARNING_MODEL:
  Network_Dimensions: ''
  Gamma: ''
  Learning_Rate: ''
  Activation_Function: ''
