SAR_Type:
  Crazyflie:
    CtrlGains:
      ## POSITION XY
      P_kp_xy: 0.4
      P_kd_xy: 0.35
      P_ki_xy: 0.07
      i_range_xy: 0.3 

      ## POSITION Z
      P_kp_z: 1.20
      P_kd_z: 0.35
      P_ki_z: 0.1
      i_range_z: 0.25

      ## ORIENTATION XY
      R_kp_xy: 0.004
      R_kd_xy: 0.0017
      R_ki_xy: 0.0
      i_range_R_xy: 1.0

      ## ORIENTATION Z
      R_kp_z: 0.003
      R_kd_z: 0.001
      R_ki_z: 0.0
      i_range_R_z: 0.5

    System_Params:
      C_tf: 0.00618
      f_max: 15.0
      Prop_Dist: 0.0325

      Prop_Front: [32.5e-3, 32.5e-3]
      Prop_Rear:  [32.5e-3, 32.5e-3]

    Config:
      ## THESE INERTIAL VALUES ARE ONLY FOR CONTROLLER, NOT SIMULATION PHYSICS
      Base_Model:       # Crazyflie Base_Model
        Initials: BM
        Mass: 34.3e-3   # [kg]
        Ixx: 15.83e-6   # [kg*m^2]
        Iyy: 17.00e-6   # [kg*m^2]
        Izz: 31.19e-6   # [kg*m^2] 

      Camera_Model:       # Crazyflie Base_Model
        Initials: Camera_Model
        Mass: 34.3e-3   # [kg]
        Ixx: 15.83e-6   # [kg*m^2]
        Iyy: 17.00e-6   # [kg*m^2]
        Izz: 31.19e-6   # [kg*m^2] 

      ####################################
      #    Leg Design Analysis Models
      ####################################

      ## ==================== 
      ##  05 DEG LEG DESIGNS     
      ## ==================== 
      A05_L50_K08: 
        Initials: A05_L50_K08
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.05  # Leg Length [m]
        Leg_Stiffness: 8  # Leg Stiffness [N*mm/rad]

      A05_L50_K32: 
        Initials: A05_L50_K32
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      A05_L50_K64: 
        Initials: A05_L50_K64
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      # =============================  

      A05_L75_K08: 
        Initials: A05_L75_K08
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 8  # Leg Stiffness [N*mm/rad]

      A05_L75_K32: 
        Initials: A05_L75_K32
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      A05_L75_K64: 
        Initials: A05_L75_K64
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      # ============================= 

      A05_L100_K08: 
        Initials: A05_L100_K08
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 8  # Leg Stiffness [N*mm/rad]

      A05_L100_K32: 
        Initials: A05_L100_K32
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      A05_L100_K64: 
        Initials: A05_L100_K64
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]


      ## ==================== 
      ##  20 DEG LEG DESIGNS     
      ## ==================== 
      A20_L50_K08: 
        Initials: A20_L50_K08
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      A20_L50_K32: 
        Initials: A20_L50_K32
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      A20_L50_K64: 
        Initials: A20_L50_K64
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      # ============================= 

      A20_L75_K08: 
        Initials: A20_L75_K08
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      A20_L75_K32: 
        Initials: A20_L75_K32
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      A20_L75_K64: 
        Initials: A20_L75_K64
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      # ============================= 

      A20_L100_K08: 
        Initials: A20_L100_K08
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      A20_L100_K32: 
        Initials: A20_L100_K32
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      A20_L100_K64: 
        Initials: A20_L100_K64
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]


      ## ==================== 
      ##  30 DEG LEG DESIGNS     
      ## ==================== 
      A30_L50_K08: 
        Initials: A30_L50_K08
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      A30_L50_K32: 
        Initials: A30_L50_K32
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      A30_L50_K64: 
        Initials: A30_L50_K64
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      # ============================= 

      A30_L75_K08: 
        Initials: A30_L75_K08
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

        Gamma: 30       # [deg]
        Length: 75      # [m]
        Stiffness: 8    # [N*mm/rad]

      A30_L75_K32: 
        Initials: A30_L75_K32
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      A30_L75_K64: 
        Initials: A30_L75_K64
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      # ============================= 

      A30_L100_K08: 
        Initials: A30_L100_K08
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      A30_L100_K32: 
        Initials: A30_L100_K32
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      A30_L100_K64: 
        Initials: A30_L100_K64
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]


      ## ==================== 
      ##  60 DEG LEG DESIGNS     
      ## ==================== 
      A60_L50_K08: 
        Initials: A60_L50_K08
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      A60_L50_K32: 
        Initials: A60_L50_K32
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      A60_L50_K64: 
        Initials: A60_L50_K64
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      # ============================= 

      A60_L75_K08: 
        Initials: A60_L75_K08
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      A60_L75_K32: 
        Initials: A60_L75_K32
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      A60_L75_K64: 
        Initials: A60_L75_K64
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      # ============================= 

      A60_L100_K08: 
        Initials: A60_L100_K08
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      A60_L100_K32: 
        Initials: A60_L100_K32
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]

      A60_L100_K64: 
        Initials: A60_L100_K64
        Mass: 38.1e-3     # [kg]
        Ixx: 27.93e-6     # [kg*m^2]
        Iyy: 30.46e-6     # [kg*m^2]
        Izz: 47.12e-6     # [kg*m^2] 

        Leg_Angle: 5      # Leg Angle [deg]
        Leg_Length: 0.1   # Leg Length [m]
        Leg_Stiffness: 64 # Leg Stiffness [N*mm/rad]


  Big_Quad:
      CtrlGains:
        ## POSITION XY
        P_kp_xy: 0.4
        P_kd_xy: 0.35
        P_ki_xy: 0.07
        i_range_xy: 0.3 

        ## POSITION Z
        P_kp_z: 1.20
        P_kd_z: 0.35
        P_ki_z: 0.1
        i_range_z: 0.25

        ## ORIENTATION XY
        R_kp_xy: 0.004
        R_kd_xy: 0.0017
        R_ki_xy: 0.0
        i_range_R_xy: 1.0

        ## ORIENTATION Z
        R_kp_z: 0.003
        R_kd_z: 0.001
        R_ki_z: 0.0
        i_range_R_z: 0.5

      System_Params:
        Prop_Dist: 0.05
        C_tf: 0.00618
        f_max: 30.0


      ####################################
      #   Not Experimentally Measured
      ####################################
      
      Big_Quad: # Crazyflie Big-Quad
        Initials: BQ
        Mass: 80.0e-3   # [kg]
        Ixx: 15.83e-6   # [kg*m^2]
        Iyy: 17.00e-6   # [kg*m^2]
        Izz: 31.19e-6   # [kg*m^2] 



  


      

    

