PLANE_SETTINGS:
  Plane_Type: Landing_Surface
  Plane_Config: Checkerboard_L02
SAR_SETTINGS:
  SAR_Type: Crazyflie
  SAR_Config: A20_L75_K08
CAM_SETTINGS:
  Cam_Config: None
  Cam_Active: false
ENV_SETTINGS:
  Env_Name: SAR_Sim_DeepRL_Env
  Vel_Limts:
  - 2.0
  - 3.0
  Phi_Rel_Limits:
  - 0
  - 90
  Plane_Angle_Limits:
  - 90
  - 180
MODEL_SETTINGS:
  Mass_Std: 0.0005
  Iyy_Std: 1.5e-06
  Mass: '?'
LEARNING_MODEL:
  Policy: SACPolicy
  Observation_Layer: 4
  Network_Layers:
    pi:
    - 8
    - 8
    qf:
    - 256
    - 256
  Action_Layer: 4
  Action_Space_High:
  - 1.0
  - 1.0
  Action_Space_Low:
  - -1.0
  - -1.0
  Gamma: 0.999
  Learning_Rate: 0.002
  Activation_Function: ''
