SAR_SETTINGS:
  SAR_Type: 'Source_One_V5'
  SAR_Config: 'A30_L250'

  # Policy_Type: "PARAM_OPTIM"
  Policy_Type: "DEEP_RL_SB3" 
  # Policy_Type: "DEEP_RL_ONBOARD" 


PLANE_SETTINGS: # INITIAL PLANE POSE SETTINGS
  Plane_Type: "Landing_Surface"
  Plane_Config: "Checkerboard_L02"
  
  Pos_X_init: 3.0       # [m]
  Pos_Y_init: 1.5       # [m]
  Pos_Z_init: 3.0       # [m]
  Plane_Angle_init: 0   # [deg]


CAM_SETTINGS:
  Cam_Config: "None"
  Cam_Active: False

SAR_DC_SETTINGS:
  Console_Output: True
  Logging_Rate: 10 # [Hz]






