SAR_SETTINGS:
  SAR_Type: 'Source_One_V5'
  SAR_Config: 'A60_L250'

  # Policy_Type: "PARAM_OPTIM"
  # Policy_Type: "DEEP_RL_SB3" 
  Policy_Type: "DEEP_RL_ONBOARD" 


PLANE_SETTINGS: # INITIAL PLANE POSE SETTINGS
  Plane_Type: "Landing_Cage_Platform"
  Plane_Config: "Landing_Platform"
  
  Pos_X_init: 3.0        # [m]
  Pos_Y_init: 0.0         # [m]
  Pos_Z_init: 2.59        # [m]
  Plane_Angle_init: 90     # [deg]


CAM_SETTINGS:
  Cam_Config: "None"
  Cam_Active: False

SAR_DC_SETTINGS:
  Console_Output: True
  Logging_Rate: 10 # [Hz]


stereo:
  stereo_image_proc:
    prefilter_size: 11
    prefilter_cap: 31
    correlation_window_size: 21
    min_disparity: 0
    disparity_range: 32
    uniqueness_ratio: 0
    texture_threshold: 10
    speckle_size: 950
    speckle_range: 4
    P1: 200
    P2: 400
    disp12MaxDiff: 0





