DATA_TYPE: "SIM"


SAR_SETTINGS:
  SAR_Type: "Source_One_V5"
  SAR_Config: "Base_Model"

  Policy_Type: "PARAM_OPTIM"
  # Policy_Type: "DEEP_RL_SB3" 
  # Policy_Type: "DEEP_RL_ONBOARD" 

CAM_SETTINGS:
  Cam_Config: "None"
  Cam_Active: False

PLANE_SETTINGS: # INITIAL PLANE POSE SETTINGS
  Plane_Type: "Landing_Surface"
  Plane_Config: "Checkerboard_L02"
  
  Plane_Angle: 180 # [deg]
  Pos_X: 0.0    # [m]
  Pos_Y: 0.0    # [m]
  Pos_Z: 2.0    # [m]

GROUND_SETTINGS:
  Ground_Type: "Ground_Surface"
  Ground_Config: "Debug"


SIM_SETTINGS:
  GUI_Flag: True
  Pause_Flag: False
  Sim_Speed: 1.0
  Sim_Slowdown_Speed: 0.2
  Landing_Slowdown_Flag: True

SAR_DC_SETTINGS:
  Console_Output: True
  Logging_Rate: 10 # [Hz]






