DATA_TYPE: "SIM"


SAR_SETTINGS:
  SAR_Type: "Impulse_Micro"
  SAR_Config: "A60_L150"

  Policy_Type: "PARAM_OPTIM"
  # Policy_Type: "DEEP_RL_SB3" 
  # Policy_Type: "DEEP_RL_ONBOARD" 


PLANE_SETTINGS: # INITIAL PLANE POSE SETTINGS
  Plane_Type: "Landing_Surface"
  Plane_Config: "Checkerboard_L02"
  
  Plane_Angle: 0 # [deg]
  Pos_X: 0.0    # [m]
  Pos_Y: 0.0    # [m]
  Pos_Z: 2.0    # [m]

GROUND_SETTINGS:
  Ground_Type: "Ground_Surface"
  Ground_Config: "None"


SIM_SETTINGS:
  GUI_Flag: True
  Pause_Flag: False
  Sim_Speed: 0.5
  Sim_Slowdown_Speed: 0.1
  Landing_Slowdown_Flag: True
  Vicon_Delay: 1 # [ms]


CAM_SETTINGS:
  Cam_Config: "None"
  Cam_Active: False

SAR_DC_SETTINGS:
  Console_Output: True
  Logging_Rate: 10 # [Hz]






