DATA_TYPE: "SIM"

GROUND_SETTINGS:
  Ground_Type: "Ground_Surface"
  Ground_Config: "None"

SIM_SETTINGS:
  GUI_Flag: True
  Pause_Flag: False
  Sim_Speed: 0.5
  Sim_Slowdown_Speed: 0.3
  Landing_Slowdown_Flag: True
  Vicon_Delay: 15 # [ms]




