geometry_msgs/Pose Pose
geometry_msgs/Twist Twist
float64 Tau
float64 OFx
float64 OFy
float64 RREV
float64 D_ceil

float64[4] FM
uint32[4] MS_PWM

float64 NN_flip
float64 NN_policy

geometry_msgs/Vector3 x_d
geometry_msgs/Vector3 v_d
geometry_msgs/Vector3 a_d



bool flip_flag
geometry_msgs/Pose Pose_tr
geometry_msgs/Twist Twist_tr
float64 Tau_tr
float64 OFx_tr
float64 OFy_tr
float64 RREV_tr

float64[] FM_flip
bool[] NN_spacer

float64 NN_tr_flip
float64 NN_tr_policy


