geometry_msgs/Pose Pose
geometry_msgs/Twist Twist
float64 Tau
float64 OFx
float64 OFy
float64 D_ceil

float64 Tau_est
float64 OFx_est
float64 OFy_est

float64[4] FM
float64[4] MotorThrusts
uint32[4] MS_PWM

float64 Tau_thr
float64 G1

float64 NN_flip
float64 NN_policy

geometry_msgs/Vector3 x_d
geometry_msgs/Vector3 v_d
geometry_msgs/Vector3 a_d



bool flip_flag
geometry_msgs/Pose Pose_tr
geometry_msgs/Twist Twist_tr
float64 Tau_tr
float64 OFx_tr
float64 OFy_tr
float64 D_ceil_tr

float64[4] FM_flip

float64 Policy_Flip_tr
float64 Policy_Action_tr


