

geometry_msgs/PoseStamped Pose
geometry_msgs/Twist Twist
float64 Tau
float64 OFx
float64 OFy
float64 RREV
float64 D_ceil
float64 NN_flip
float64 NN_policy
float64[] FM
uint32[] MS_PWM

bool flip_flag
geometry_msgs/PoseStamped Pose_tr
geometry_msgs/Twist Twist_tr
float64 Tau_tr
float64 OFx_tr
float64 OFy_tr
float64 RREV_tr
float64 NN_tr_flip
float64 NN_tr_policy
float64[] FM_flip
bool[] NN_spacer


