# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Connect_Indicator = QtWidgets.QProgressBar(self.centralwidget)
        self.Connect_Indicator.setProperty("value", 0)
        self.Connect_Indicator.setInvertedAppearance(False)
        self.Connect_Indicator.setObjectName("Connect_Indicator")
        self.horizontalLayout.addWidget(self.Connect_Indicator)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.K_ep_num = QtWidgets.QLCDNumber(self.centralwidget)
        self.K_ep_num.setObjectName("K_ep_num")
        self.horizontalLayout.addWidget(self.K_ep_num)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.K_run_num = QtWidgets.QLCDNumber(self.centralwidget)
        self.K_run_num.setDigitCount(5)
        self.K_run_num.setProperty("value", 0.0)
        self.K_run_num.setObjectName("K_run_num")
        self.horizontalLayout.addWidget(self.K_run_num)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.Battery_Voltage = QtWidgets.QProgressBar(self.centralwidget)
        self.Battery_Voltage.setProperty("value", 0)
        self.Battery_Voltage.setObjectName("Battery_Voltage")
        self.horizontalLayout.addWidget(self.Battery_Voltage)
        self.horizontalLayout.setStretch(6, 80)
        self.horizontalLayout.setStretch(7, 20)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.Tab_State = QtWidgets.QWidget()
        self.Tab_State.setObjectName("Tab_State")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Tab_State)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_8 = QtWidgets.QFrame(self.Tab_State)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setLineWidth(1)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_34 = QtWidgets.QLabel(self.frame_8)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_12.addWidget(self.label_34)
        self.widget_11 = Pos_Widget(self.frame_8)
        self.widget_11.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_12.addWidget(self.widget_11)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_35 = QtWidgets.QLabel(self.frame_8)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_18.addWidget(self.label_35)
        self.line_26 = QtWidgets.QFrame(self.frame_8)
        self.line_26.setStyleSheet("color: rgb(214, 39, 40);")
        self.line_26.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_26.setLineWidth(2)
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setObjectName("line_26")
        self.horizontalLayout_18.addWidget(self.line_26)
        self.label_36 = QtWidgets.QLabel(self.frame_8)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_18.addWidget(self.label_36)
        self.line_27 = QtWidgets.QFrame(self.frame_8)
        self.line_27.setStyleSheet("color: rgb(44, 160, 44);")
        self.line_27.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_27.setLineWidth(2)
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setObjectName("line_27")
        self.horizontalLayout_18.addWidget(self.line_27)
        self.label_37 = QtWidgets.QLabel(self.frame_8)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_18.addWidget(self.label_37)
        self.line_28 = QtWidgets.QFrame(self.frame_8)
        self.line_28.setStyleSheet("color: rgb(31, 119, 180);")
        self.line_28.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_28.setLineWidth(2)
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setObjectName("line_28")
        self.horizontalLayout_18.addWidget(self.line_28)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem2)
        self.horizontalLayout_18.setStretch(0, 10)
        self.horizontalLayout_18.setStretch(1, 5)
        self.horizontalLayout_18.setStretch(2, 10)
        self.horizontalLayout_18.setStretch(3, 5)
        self.horizontalLayout_18.setStretch(4, 10)
        self.horizontalLayout_18.setStretch(5, 5)
        self.horizontalLayout_18.setStretch(6, 2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_18)
        self.verticalLayout_12.setStretch(0, 1)
        self.verticalLayout_12.setStretch(1, 10)
        self.verticalLayout_12.setStretch(2, 1)
        self.horizontalLayout_14.addLayout(self.verticalLayout_12)
        self.horizontalLayout_2.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.Tab_State)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setLineWidth(1)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_39 = QtWidgets.QLabel(self.frame_9)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_16.addWidget(self.label_39)
        self.widget_14 = Vel_Widget(self.frame_9)
        self.widget_14.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_16.addWidget(self.widget_14)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_44 = QtWidgets.QLabel(self.frame_9)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_27.addWidget(self.label_44)
        self.line_29 = QtWidgets.QFrame(self.frame_9)
        self.line_29.setStyleSheet("color: rgb(214, 39, 40);")
        self.line_29.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_29.setLineWidth(2)
        self.line_29.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_29.setObjectName("line_29")
        self.horizontalLayout_27.addWidget(self.line_29)
        self.label_45 = QtWidgets.QLabel(self.frame_9)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_27.addWidget(self.label_45)
        self.line_30 = QtWidgets.QFrame(self.frame_9)
        self.line_30.setStyleSheet("color: rgb(44, 160, 44);")
        self.line_30.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_30.setLineWidth(2)
        self.line_30.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_30.setObjectName("line_30")
        self.horizontalLayout_27.addWidget(self.line_30)
        self.label_48 = QtWidgets.QLabel(self.frame_9)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_27.addWidget(self.label_48)
        self.line_31 = QtWidgets.QFrame(self.frame_9)
        self.line_31.setStyleSheet("color: rgb(31, 119, 180);")
        self.line_31.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_31.setLineWidth(2)
        self.line_31.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_31.setObjectName("line_31")
        self.horizontalLayout_27.addWidget(self.line_31)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem3)
        self.horizontalLayout_27.setStretch(0, 10)
        self.horizontalLayout_27.setStretch(1, 5)
        self.horizontalLayout_27.setStretch(2, 10)
        self.horizontalLayout_27.setStretch(3, 5)
        self.horizontalLayout_27.setStretch(4, 10)
        self.horizontalLayout_27.setStretch(5, 5)
        self.horizontalLayout_27.setStretch(6, 2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_27)
        self.verticalLayout_16.setStretch(0, 1)
        self.verticalLayout_16.setStretch(1, 10)
        self.verticalLayout_16.setStretch(2, 1)
        self.horizontalLayout_19.addLayout(self.verticalLayout_16)
        self.horizontalLayout_2.addWidget(self.frame_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.frame_10 = QtWidgets.QFrame(self.Tab_State)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_10.setLineWidth(1)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_52 = QtWidgets.QLabel(self.frame_10)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_17.addWidget(self.label_52)
        self.widget_15 = PWM_Widget(self.frame_10)
        self.widget_15.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_17.addWidget(self.widget_15)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_54 = QtWidgets.QLabel(self.frame_10)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_29.addWidget(self.label_54)
        self.line_36 = QtWidgets.QFrame(self.frame_10)
        self.line_36.setStyleSheet("color: rgb(214, 39, 40);")
        self.line_36.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_36.setLineWidth(2)
        self.line_36.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_36.setObjectName("line_36")
        self.horizontalLayout_29.addWidget(self.line_36)
        self.label_55 = QtWidgets.QLabel(self.frame_10)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_29.addWidget(self.label_55)
        self.line_39 = QtWidgets.QFrame(self.frame_10)
        self.line_39.setStyleSheet("color: rgb(44, 160, 44);")
        self.line_39.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_39.setLineWidth(2)
        self.line_39.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_39.setObjectName("line_39")
        self.horizontalLayout_29.addWidget(self.line_39)
        self.label_56 = QtWidgets.QLabel(self.frame_10)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_29.addWidget(self.label_56)
        self.line_41 = QtWidgets.QFrame(self.frame_10)
        self.line_41.setStyleSheet("color: rgb(31, 119, 180);")
        self.line_41.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_41.setLineWidth(2)
        self.line_41.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_41.setObjectName("line_41")
        self.horizontalLayout_29.addWidget(self.line_41)
        self.label_61 = QtWidgets.QLabel(self.frame_10)
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_29.addWidget(self.label_61)
        self.line_45 = QtWidgets.QFrame(self.frame_10)
        self.line_45.setStyleSheet("color: rgb(255, 127, 14);")
        self.line_45.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_45.setLineWidth(2)
        self.line_45.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_45.setObjectName("line_45")
        self.horizontalLayout_29.addWidget(self.line_45)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem4)
        self.horizontalLayout_29.setStretch(0, 10)
        self.horizontalLayout_29.setStretch(1, 5)
        self.horizontalLayout_29.setStretch(2, 10)
        self.horizontalLayout_29.setStretch(3, 5)
        self.horizontalLayout_29.setStretch(4, 10)
        self.horizontalLayout_29.setStretch(5, 5)
        self.horizontalLayout_29.setStretch(6, 10)
        self.horizontalLayout_29.setStretch(7, 5)
        self.horizontalLayout_29.setStretch(8, 2)
        self.verticalLayout_17.addLayout(self.horizontalLayout_29)
        self.verticalLayout_17.setStretch(0, 1)
        self.verticalLayout_17.setStretch(1, 10)
        self.verticalLayout_17.setStretch(2, 1)
        self.horizontalLayout_28.addLayout(self.verticalLayout_17)
        self.verticalLayout_2.addWidget(self.frame_10)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.Tab_State, "")
        self.Tab_Misc = QtWidgets.QWidget()
        self.Tab_Misc.setObjectName("Tab_Misc")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Tab_Misc)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.Tab_Misc)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_8.addWidget(self.label_22)
        self.widget_6 = dist_Widget(self.frame)
        self.widget_6.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_8.addWidget(self.widget_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_8.addWidget(self.label_23)
        self.line_17 = QtWidgets.QFrame(self.frame)
        self.line_17.setStyleSheet("color: rgb(204, 0, 0);\n"
"color: rgb(214, 39, 40);")
        self.line_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_17.setLineWidth(2)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setObjectName("line_17")
        self.horizontalLayout_8.addWidget(self.line_17)
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_8.addWidget(self.label_24)
        self.line_18 = QtWidgets.QFrame(self.frame)
        self.line_18.setStyleSheet("color: rgb(44, 160, 44);")
        self.line_18.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_18.setLineWidth(2)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setObjectName("line_18")
        self.horizontalLayout_8.addWidget(self.line_18)
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_8.addWidget(self.label_25)
        self.line_19 = QtWidgets.QFrame(self.frame)
        self.line_19.setStyleSheet("color: rgb(31, 119, 180);")
        self.line_19.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_19.setLineWidth(2)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setObjectName("line_19")
        self.horizontalLayout_8.addWidget(self.line_19)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.horizontalLayout_8.setStretch(0, 10)
        self.horizontalLayout_8.setStretch(1, 5)
        self.horizontalLayout_8.setStretch(2, 10)
        self.horizontalLayout_8.setStretch(3, 5)
        self.horizontalLayout_8.setStretch(4, 10)
        self.horizontalLayout_8.setStretch(5, 5)
        self.horizontalLayout_8.setStretch(6, 2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 10)
        self.verticalLayout_8.setStretch(2, 1)
        self.horizontalLayout_9.addLayout(self.verticalLayout_8)
        self.horizontalLayout_5.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.Tab_Misc)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_26 = QtWidgets.QLabel(self.frame_2)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_9.addWidget(self.label_26)
        self.widget_7 = Eul_Widget(self.frame_2)
        self.widget_7.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_9.addWidget(self.widget_7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_27 = QtWidgets.QLabel(self.frame_2)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_11.addWidget(self.label_27)
        self.line_20 = QtWidgets.QFrame(self.frame_2)
        self.line_20.setStyleSheet("color: rgb(214, 39, 40);")
        self.line_20.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_20.setLineWidth(2)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setObjectName("line_20")
        self.horizontalLayout_11.addWidget(self.line_20)
        self.label_28 = QtWidgets.QLabel(self.frame_2)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_11.addWidget(self.label_28)
        self.line_21 = QtWidgets.QFrame(self.frame_2)
        self.line_21.setStyleSheet("color: rgb(44, 160, 44);")
        self.line_21.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_21.setLineWidth(2)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setObjectName("line_21")
        self.horizontalLayout_11.addWidget(self.line_21)
        self.label_29 = QtWidgets.QLabel(self.frame_2)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_11.addWidget(self.label_29)
        self.line_22 = QtWidgets.QFrame(self.frame_2)
        self.line_22.setStyleSheet("color: rgb(31, 119, 180);")
        self.line_22.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_22.setLineWidth(2)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setObjectName("line_22")
        self.horizontalLayout_11.addWidget(self.line_22)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.horizontalLayout_11.setStretch(0, 10)
        self.horizontalLayout_11.setStretch(1, 5)
        self.horizontalLayout_11.setStretch(2, 10)
        self.horizontalLayout_11.setStretch(3, 5)
        self.horizontalLayout_11.setStretch(4, 10)
        self.horizontalLayout_11.setStretch(5, 5)
        self.horizontalLayout_11.setStretch(6, 2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 10)
        self.verticalLayout_9.setStretch(2, 1)
        self.horizontalLayout_10.addLayout(self.verticalLayout_9)
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.horizontalLayout_5.setStretch(0, 50)
        self.horizontalLayout_5.setStretch(1, 50)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_3 = QtWidgets.QFrame(self.Tab_Misc)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(1)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_30 = QtWidgets.QLabel(self.frame_3)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_10.addWidget(self.label_30)
        self.widget_8 = OF_Widget(self.frame_3)
        self.widget_8.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_10.addWidget(self.widget_8)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_31 = QtWidgets.QLabel(self.frame_3)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_15.addWidget(self.label_31)
        self.line_23 = QtWidgets.QFrame(self.frame_3)
        self.line_23.setStyleSheet("color: rgb(214, 39, 40);")
        self.line_23.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_23.setLineWidth(2)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setObjectName("line_23")
        self.horizontalLayout_15.addWidget(self.line_23)
        self.label_32 = QtWidgets.QLabel(self.frame_3)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_15.addWidget(self.label_32)
        self.line_24 = QtWidgets.QFrame(self.frame_3)
        self.line_24.setStyleSheet("color: rgb(44, 160, 44);")
        self.line_24.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_24.setLineWidth(2)
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setObjectName("line_24")
        self.horizontalLayout_15.addWidget(self.line_24)
        self.label_33 = QtWidgets.QLabel(self.frame_3)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_15.addWidget(self.label_33)
        self.line_25 = QtWidgets.QFrame(self.frame_3)
        self.line_25.setStyleSheet("color: rgb(31, 119, 180);")
        self.line_25.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_25.setLineWidth(2)
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setObjectName("line_25")
        self.horizontalLayout_15.addWidget(self.line_25)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem7)
        self.horizontalLayout_15.setStretch(0, 10)
        self.horizontalLayout_15.setStretch(1, 5)
        self.horizontalLayout_15.setStretch(2, 10)
        self.horizontalLayout_15.setStretch(3, 5)
        self.horizontalLayout_15.setStretch(4, 10)
        self.horizontalLayout_15.setStretch(5, 5)
        self.horizontalLayout_15.setStretch(6, 2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.verticalLayout_10.setStretch(0, 1)
        self.verticalLayout_10.setStretch(1, 10)
        self.verticalLayout_10.setStretch(2, 1)
        self.horizontalLayout_12.addLayout(self.verticalLayout_10)
        self.horizontalLayout_7.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.Tab_Misc)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(1)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_40 = QtWidgets.QLabel(self.frame_4)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_11.addWidget(self.label_40)
        self.widget_9 = Omega_Widget(self.frame_4)
        self.widget_9.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_11.addWidget(self.widget_9)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_41 = QtWidgets.QLabel(self.frame_4)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_17.addWidget(self.label_41)
        self.line_32 = QtWidgets.QFrame(self.frame_4)
        self.line_32.setStyleSheet("color: rgb(214, 39, 40);")
        self.line_32.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_32.setLineWidth(2)
        self.line_32.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_32.setObjectName("line_32")
        self.horizontalLayout_17.addWidget(self.line_32)
        self.label_42 = QtWidgets.QLabel(self.frame_4)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_17.addWidget(self.label_42)
        self.line_33 = QtWidgets.QFrame(self.frame_4)
        self.line_33.setStyleSheet("color: rgb(44, 160, 44);")
        self.line_33.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_33.setLineWidth(2)
        self.line_33.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_33.setObjectName("line_33")
        self.horizontalLayout_17.addWidget(self.line_33)
        self.label_43 = QtWidgets.QLabel(self.frame_4)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_17.addWidget(self.label_43)
        self.line_34 = QtWidgets.QFrame(self.frame_4)
        self.line_34.setStyleSheet("color: rgb(31, 119, 180);")
        self.line_34.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_34.setLineWidth(2)
        self.line_34.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_34.setObjectName("line_34")
        self.horizontalLayout_17.addWidget(self.line_34)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem8)
        self.horizontalLayout_17.setStretch(0, 10)
        self.horizontalLayout_17.setStretch(1, 5)
        self.horizontalLayout_17.setStretch(2, 10)
        self.horizontalLayout_17.setStretch(3, 5)
        self.horizontalLayout_17.setStretch(4, 10)
        self.horizontalLayout_17.setStretch(5, 5)
        self.horizontalLayout_17.setStretch(6, 2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_17)
        self.verticalLayout_11.setStretch(0, 1)
        self.verticalLayout_11.setStretch(1, 10)
        self.verticalLayout_11.setStretch(2, 1)
        self.horizontalLayout_16.addLayout(self.verticalLayout_11)
        self.horizontalLayout_7.addWidget(self.frame_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.Tab_Misc, "")
        self.Tab_Onboard = QtWidgets.QWidget()
        self.Tab_Onboard.setObjectName("Tab_Onboard")
        self.tabWidget.addTab(self.Tab_Onboard, "")
        self.Tab_RL = QtWidgets.QWidget()
        self.Tab_RL.setObjectName("Tab_RL")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.Tab_RL)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_5 = QtWidgets.QFrame(self.Tab_RL)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setLineWidth(1)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_38 = QtWidgets.QLabel(self.frame_5)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_13.addWidget(self.label_38)
        self.widget_10 = RL_Widget(self.frame_5)
        self.widget_10.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_13.addWidget(self.widget_10)
        self.verticalLayout_13.setStretch(1, 10)
        self.horizontalLayout_13.addLayout(self.verticalLayout_13)
        self.verticalLayout_6.addWidget(self.frame_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_6 = QtWidgets.QFrame(self.Tab_RL)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setLineWidth(1)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_46 = QtWidgets.QLabel(self.frame_6)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_14.addWidget(self.label_46)
        self.widget_12 = Mu_Widget(self.frame_6)
        self.widget_12.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_14.addWidget(self.widget_12)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_47 = QtWidgets.QLabel(self.frame_6)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_21.addWidget(self.label_47)
        self.line_35 = QtWidgets.QFrame(self.frame_6)
        self.line_35.setStyleSheet("color: rgb(255,127,14);")
        self.line_35.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_35.setLineWidth(2)
        self.line_35.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_35.setObjectName("line_35")
        self.horizontalLayout_21.addWidget(self.line_35)
        self.label_49 = QtWidgets.QLabel(self.frame_6)
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_21.addWidget(self.label_49)
        self.line_37 = QtWidgets.QFrame(self.frame_6)
        self.line_37.setStyleSheet("color: rgb(31, 119, 180);")
        self.line_37.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_37.setLineWidth(2)
        self.line_37.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_37.setObjectName("line_37")
        self.horizontalLayout_21.addWidget(self.line_37)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem9)
        self.horizontalLayout_21.setStretch(0, 10)
        self.horizontalLayout_21.setStretch(1, 5)
        self.horizontalLayout_21.setStretch(2, 10)
        self.horizontalLayout_21.setStretch(3, 5)
        self.horizontalLayout_21.setStretch(4, 2)
        self.verticalLayout_14.addLayout(self.horizontalLayout_21)
        self.verticalLayout_14.setStretch(1, 10)
        self.verticalLayout_14.setStretch(2, 1)
        self.horizontalLayout_20.addLayout(self.verticalLayout_14)
        self.horizontalLayout_6.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.Tab_RL)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setLineWidth(1)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_50 = QtWidgets.QLabel(self.frame_7)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_15.addWidget(self.label_50)
        self.widget_13 = Sig_Widget(self.frame_7)
        self.widget_13.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_15.addWidget(self.widget_13)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_51 = QtWidgets.QLabel(self.frame_7)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_23.addWidget(self.label_51)
        self.line_38 = QtWidgets.QFrame(self.frame_7)
        self.line_38.setStyleSheet("color: rgb(255,127,14);")
        self.line_38.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_38.setLineWidth(2)
        self.line_38.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_38.setObjectName("line_38")
        self.horizontalLayout_23.addWidget(self.line_38)
        self.label_53 = QtWidgets.QLabel(self.frame_7)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_23.addWidget(self.label_53)
        self.line_40 = QtWidgets.QFrame(self.frame_7)
        self.line_40.setStyleSheet("color: rgb(31,119,180);")
        self.line_40.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_40.setLineWidth(2)
        self.line_40.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_40.setObjectName("line_40")
        self.horizontalLayout_23.addWidget(self.line_40)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem10)
        self.horizontalLayout_23.setStretch(0, 10)
        self.horizontalLayout_23.setStretch(1, 5)
        self.horizontalLayout_23.setStretch(2, 10)
        self.horizontalLayout_23.setStretch(3, 5)
        self.horizontalLayout_23.setStretch(4, 2)
        self.verticalLayout_15.addLayout(self.horizontalLayout_23)
        self.verticalLayout_15.setStretch(1, 10)
        self.verticalLayout_15.setStretch(2, 1)
        self.horizontalLayout_22.addLayout(self.verticalLayout_15)
        self.horizontalLayout_6.addWidget(self.frame_7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_24.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.Tab_RL, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_13.setText(_translate("MainWindow", "Episode:"))
        self.label_14.setText(_translate("MainWindow", "Run:"))
        self.label_34.setText(_translate("MainWindow", "Position - [m]"))
        self.label_35.setText(_translate("MainWindow", "X"))
        self.label_36.setText(_translate("MainWindow", "Y"))
        self.label_37.setText(_translate("MainWindow", "Z"))
        self.label_39.setText(_translate("MainWindow", "Velocity - [m/s]"))
        self.label_44.setText(_translate("MainWindow", "X"))
        self.label_45.setText(_translate("MainWindow", "Y"))
        self.label_48.setText(_translate("MainWindow", "Z"))
        self.label_52.setText(_translate("MainWindow", "Motor Commands - [pwm]"))
        self.label_54.setText(_translate("MainWindow", "M1"))
        self.label_55.setText(_translate("MainWindow", "M2"))
        self.label_56.setText(_translate("MainWindow", "M3"))
        self.label_61.setText(_translate("MainWindow", "M4"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_State), _translate("MainWindow", "State Data"))
        self.label_22.setText(_translate("MainWindow", "Distance Estimate"))
        self.label_23.setText(_translate("MainWindow", "X"))
        self.label_24.setText(_translate("MainWindow", "Y"))
        self.label_25.setText(_translate("MainWindow", "Z"))
        self.label_26.setText(_translate("MainWindow", "Attitude - [deg]"))
        self.label_27.setText(_translate("MainWindow", "Roll"))
        self.label_28.setText(_translate("MainWindow", "Pitch"))
        self.label_29.setText(_translate("MainWindow", "Yaw"))
        self.label_30.setText(_translate("MainWindow", "Optical Flow"))
        self.label_31.setText(_translate("MainWindow", "RREV"))
        self.label_32.setText(_translate("MainWindow", "OFx"))
        self.label_33.setText(_translate("MainWindow", "OFy"))
        self.label_40.setText(_translate("MainWindow", "Ang. Vel - [rad/s]"))
        self.label_41.setText(_translate("MainWindow", "Wx"))
        self.label_42.setText(_translate("MainWindow", "Wy"))
        self.label_43.setText(_translate("MainWindow", "Wz"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Misc), _translate("MainWindow", "Misc Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Onboard), _translate("MainWindow", "Sensory Data"))
        self.label_38.setText(_translate("MainWindow", "Reward Plot"))
        self.label_46.setText(_translate("MainWindow", "Mu"))
        self.label_47.setText(_translate("MainWindow", "Mu_1"))
        self.label_49.setText(_translate("MainWindow", "Mu_2"))
        self.label_50.setText(_translate("MainWindow", "Sigma"))
        self.label_51.setText(_translate("MainWindow", "Sig_1"))
        self.label_53.setText(_translate("MainWindow", "Sig_2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_RL), _translate("MainWindow", "RL Data"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
from Plotter import Eul_Widget, Mu_Widget, OF_Widget, Omega_Widget, PWM_Widget, Pos_Widget, RL_Widget, Sig_Widget, Vel_Widget, dist_Widget
