SAR_SETTINGS:
  SAR_Type: Source_One_V5
  SAR_Config: A30_L200
PLANE_SETTINGS:
  Plane_Type: Landing_Surface
  Plane_Config: Checkerboard_L02
ENV_SETTINGS:
  Env_Name: SAR_2D_DeepRL_Env
  V_mag_Limts:
  - 1.0
  - 4.0
  V_angle_Limits:
  - 10
  - 170
  Plane_Angle_Limits:
  - 0
  - 180
  Ang_Acc_Limits:
  - -100
  - 100
MODEL_SETTINGS:
  Mass_Std: 0.0
  Iyy_Std: 0.0001728
  Ref_Mass: 0.7917
  Ref_Ixx: 0.00622
  Ref_Iyy: 0.00576
  Ref_Izz: 0.00633
  L_eff: 0.20809
  Gamma_eff: 26.12
  Forward_Reach: 0.15
LEARNING_MODEL:
  Policy: SACPolicy
  Observation_Layer: 4
  Network_Layers:
    pi:
    - 10
    - 10
    - 10
    qf:
    - 256
    - 256
    - 256
  Action_Layer: 4
  Action_Space_High:
  - 1.0
  - 1.0
  Action_Space_Low:
  - -1.0
  - -1.0
  Gamma: 0.999
  Learning_Rate: 0.002
REWARD_SETTINGS:
  W_Dist: 0.1
  W_tau_cr: 0.1
  W_tx: 2.0
  W_LT: 1.0
  W_GM: 1.0
  W_Phi_rel: 2.0
  W_Legs: 2.0
