all: controller
controller:controller.cpp math_linear_algebra.cpp
	g++ -Wall -I../include controller.cpp math_linear_algebra.cpp -o ../controller -lpthread
	#g++ controller.cpp -o ../controller -lboost_system -lboost_thread
