ENV_SETTINGS:
  Env_Name: SAR_Env_2D
  V_mag_Limts:
  - 1
  - 3
  V_angle_Limits:
  - -175
  - -5
  Plane_Angle_Limits:
  - 0
  - 0
MODEL_SETTINGS:
  Mass: 0.035
  Ixx: 1.58e-05
  Iyy: 1.7e-05
  Izz: 3.12e-05
  L: 0.105
  Gamma: 45.0
  PD: 0.075
LEARNING_MODEL:
  Policy: SACPolicy
  Observation_Layer: 4
  Network_Layers:
    pi:
    - 16
    - 16
    qf:
    - 256
    - 256
  Action_Layer: 4
  Action_Space_High:
  - 1.0
  - 1.0
  Action_Space_Low:
  - -1.0
  - -1.0
  Gamma: 0.999
  Learning_Rate: 0.002
  Activation_Function: ''
REWARD_SETTINGS:
  W_Dist: 0.2
  W_tau_cr: 0.0
  W_LT: 1.0
  W_GM: 0.0
  W_Phi_rel: 0.0
  W_Legs: 2.0
