<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="rrbot"
  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" />
  <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.1" />
  <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="2" />
  <!-- Link 1 -->
  <xacro:property name="height2" value="1" />
  <!-- Link 2 -->
  <xacro:property name="height3" value="1" />
  <!-- Link 3 -->
  <xacro:property name="camera_link" value="0.05" />
  <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.05" />
  <!-- Space btw top of beam and the each joint -->

  <xacro:property name="x_offset" value="72.6e-3" />
  <xacro:property name="y_offset" value="86.6e-3" />



  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find sar_gazebo)/models/rrbot/urdf/rrbot.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find sar_gazebo)/models/rrbot/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  

  <!-- Base Link -->
  <link name="link1">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://sar_gazebo/models/rrbot/meshes/SO_V5_Base_Assembly.STL"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0" iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0" izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint1" type="continuous">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="${x_offset} -${y_offset} 28.0e-3" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <!-- Middle Link -->
  <link name="link2">
    <collision>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://sar_gazebo/models/rrbot/meshes/SO_V5_Propeller.STL"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0" iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0" izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>


  <gazebo>
    <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <jointName>joint1</jointName>
      <updateRate>100.0</updateRate>
      <alwaysOn>true</alwaysOn>
    </plugin>
  </gazebo>

</robot>
