PLANE_SETTINGS:
  Plane_Model: Standard_Plane
  Plane_Angle: 180
  Plane_Pos:
    X: 0
    Y: 0
    Z: 2.0
QUAD_SETTINGS:
  CF_Type: Standard
  CF_Config: A60_L50_K08
ENV_SETTINGS:
  Environment: CF_Gazebo
  Vel_Limts:
  - 0.5
  - 3.5
  Phi_Limits:
  - 30
  - 90
LEARNING_MODEL:
  Policy: SACPolicy
  Network_Layers:
  - 12
  - 12
  Gamma: 0.999
  Learning_Rate: 0.002
  Activation_Function: ''
